# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(468, 190)
        self.FormArea = QtWidgets.QWidget(Form)
        self.FormArea.setGeometry(QtCore.QRect(0, 0, 468, 190))
        self.FormArea.setObjectName("FormArea")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.FormArea)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text = QtWidgets.QLabel(self.FormArea)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.text.setFont(font)
        self.text.setObjectName("text")
        self.verticalLayout.addWidget(self.text)
        self.progressBar = QtWidgets.QProgressBar(self.FormArea)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.fmt = QtWidgets.QLabel(self.FormArea)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.fmt.setFont(font)
        self.fmt.setObjectName("fmt")
        self.horizontalLayout_2.addWidget(self.fmt)
        self.rate = QtWidgets.QLabel(self.FormArea)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.rate.setFont(font)
        self.rate.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rate.setObjectName("rate")
        self.horizontalLayout_2.addWidget(self.rate)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.elapsed = QtWidgets.QLabel(self.FormArea)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.elapsed.setFont(font)
        self.elapsed.setText("")
        self.elapsed.setObjectName("elapsed")
        self.horizontalLayout_4.addWidget(self.elapsed)
        self.remaining = QtWidgets.QLabel(self.FormArea)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.remaining.setFont(font)
        self.remaining.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.remaining.setObjectName("remaining")
        self.horizontalLayout_4.addWidget(self.remaining)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout_13.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addLayout(self.verticalLayout_13)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.cancelBtn = QtWidgets.QPushButton(self.FormArea)
        self.cancelBtn.setObjectName("cancelBtn")
        self.horizontalLayout.addWidget(self.cancelBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.text.setText(_translate("Form", "Downloading model \"tiny\"..."))
        self.fmt.setText(_translate("Form", "68.5M/461M"))
        self.rate.setText(_translate("Form", "4.02MiB/s"))
        self.remaining.setText(_translate("Form", "Elapsed: 00:23  Remaining: 01:42"))
        self.cancelBtn.setText(_translate("Form", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
